config/routes.rb
Platform::Application.routes.draw do
  get "welcome/index"
  put "profile/upgrade"
  get "profile/show"
  get "profile/index"
  delete "profile/destroy"
  resources :rents

  devise_for :users, controllers: { registrations: "users/registrations" }

  root 'welcome#index'
  get 'rents' => 'rents#index', as: :user_root

end

app/models/rent.rb
# encoding: UTF-8
class Rent < ActiveRecord::Base
  validates_date :date_from, :on_or_before => :date_to,
                             :on_or_before_message => "穿越啦！"
  belongs_to :user

end

app/controllers/rents_controller.rb
# encoding: UTF-8
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authorization, only: [:edit, :update, :destroy]
  respond_to :html

  def index
    @rents = Rent.all
    respond_with(@rents)
  end

  def show
    respond_with(@rent)
  end

  def new
    @rent = Rent.new
    respond_with(@rent)
  end

  def edit
  end

  def create
    @rent = current_user.rent.build(rent_params)
    @rent.save
    respond_with(@rent)
  end

  def update
    @rent.update(rent_params)
    respond_with(@rent)
  end

  def destroy
    @rent.destroy
    if params[:from_profile] == 'true'
      redirect_to :back
    else
      respond_with(@rent)
    end
  end

  private
    def set_rent
      @rent = Rent.find(params[:id])
    end

    def rent_params
      params.require(:rent).permit(:title, :date_from, :date_to, :description, :telephone,
                                  :wechat, :district, :price)
    end

    def authorization
      unless rent_authorized?(current_user, @rent)
        redirect_to :back, notice: "你没有权限"
      end
    end

end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/_form.html.erb
<%= form_for(@rent) do |f| %>
  <% if @rent.errors.any? %>
    <div class="alert alert-warning">
      <h2><%= pluralize(@rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
      <% @rent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="row top30"></div>
    <div class="form-horizontal">

    <div class="form-group">
      <%= f.label '标题', class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
      <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label '起租日期', class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
      <%= f.date_field :date_from, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label '结租日期', class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
      <%= f.date_field :date_to, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label '价格$', class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
      <%= f.number_field :price, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label '联系电话', class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
      <%= f.telephone_field :telephone, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label '微信号', class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
      <%= f.text_field :wechat, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label '小区名', class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
      <%= f.text_field :district, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label '简介', class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
      <%= f.text_area :description, :rows => "10", class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="form-group text-right">
      <%= f.submit '提 交', class: "btn btn-primary" %>
      <%= link_to '返 回', :back, class: "btn btn-default"%>
    </div>
    </div>
  </div>
</div>
<% end %>

app/views/rents/edit.html.erb
<div class="page-header">
  <center><h1>编辑招租信息</h1></center>
</div>
<%= render 'form' %>

app/views/rents/index.html.erb
<div style="margin-left: 10%; margin-right: 10%">
<div class="page-header">
  <center><h1>招租信息一览</h1></center>
</div>
<div class=" text-right" >
  <%= link_to '发布招租信息', new_rent_path, class: "btn btn-default" %>
</div>
<br />
<table class="table table-striped text-center table-hover">
  <thead > 
    <tr >
      <th class="text-center">标题</th>
      <th class="text-center">起租日期</th>
      <th class="text-center">小区名</th>
      <th class="text-center">价格</th>
      <th class="text-center">招租人</th>
      <% if current_user.authority > 0 %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody class="top30">
    <% @rents.reverse_each do |rent| %>
        <tr data-link="<%= rent_path(rent) %>">
          <td><%= truncate rent.title, length: 20 %></td>
          <td><%= rent.date_from %></td>
          <td><%= truncate rent.district, length: 20 %></td>
          <% if rent.price == nil %>
            <td>未定</td>
          <% else %>
            <td><%= truncate(number_to_currency(rent.price), length: 10) %></td>
          <% end %>
          <td><%= truncate rent.user.name %></td>
          <% if current_user.authority > 0 %>
            <td><%= link_to '删除', rent, method: :delete, data: { confirm: '确定删除嘛？' } %></td>
          <% end %>
        </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/rents/new.html.erb
<div class="page-header">
  <center><h1>新的招租信息</h1></center>
</div>
<%= render 'form' %>

app/views/rents/show.html.erb
<div class="text-center">
<div class="page-header">
  <center><h2><%= @rent.title %></h2></center>
</div>
<p>
  <strong>起租日期:</strong>
  <%= @rent.date_from %>
</p>

<p>
  <strong>结租日期:</strong>
  <%= @rent.date_to %>
</p>
<p>
  <strong>招租人:</strong>
  <%= @rent.user.name %>
</p>
<p>
  <strong>价格:</strong>
  <%= number_to_currency @rent.price %>
</p>
<p>
  <strong>小区名:</strong>
  <%= @rent.district %>
</p>
<p>
  <strong>简介:</strong>
  <%= @rent.description %>
</p>
<p>
  <strong>联系电话：</strong>
  <%= @rent.telephone %><br>
  <strong>微信号：</strong>
  <%= @rent.wechat %><br>
  <strong>电子邮箱：</strong>
  <%= @rent.user.email %>
</p>
<br>
<p>
<% if rent_authorized? current_user, @rent %>
  <%= link_to '编辑', edit_rent_path(@rent) %> | 
  <%= link_to '删除', @rent, method: :delete, data: { confirm: '确定删除嘛？' } %> | 
<% end %>
<%= link_to '返回', rents_path %>
</p>
</div>